// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiM9n078hSNrVAJS8kpyjCntMtTNJJRAo',
    appId: '1:812644809997:web:2de18e9c1c82e25b93c444',
    messagingSenderId: '812644809997',
    projectId: 'campus-saga',
    authDomain: 'campus-saga.firebaseapp.com',
    databaseURL: 'https://campus-saga-default-rtdb.firebaseio.com',
    storageBucket: 'campus-saga.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkCxnJMh-Tvwt32wZFU-IBcdb7Em2ZAt4',
    appId: '1:587775658076:android:f997b8c9b91b8752b47e99',
    messagingSenderId: '587775658076',
    projectId: 'campus-saga-final',
    storageBucket: 'campus-saga-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskn_Lz92epWhK44BBDyo1Hq23-xk_YJQ',
    appId: '1:587775658076:ios:64175719fd242286b47e99',
    messagingSenderId: '587775658076',
    projectId: 'campus-saga-final',
    storageBucket: 'campus-saga-final.appspot.com',
    iosBundleId: 'com.example.campusSaga',
  );

}
